apiVersion: v2
name: multi-tenant-saas
description: A Helm chart for deploying the Multi-Tenant SaaS Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Mario Perez
    email: perezmario303@gmail.com
